apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logchimp.fullname" . }}-key
  labels:
    {{- include "logchimp.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ template "logchimp.secretKey" . }}
