apiVersion: v1
kind: Service
metadata:
  name: {{ include "logchimp.fullname" . }}
  labels:
    {{- include "logchimp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: node
      protocol: TCP
      name: http
  selector:
    {{- include "logchimp.selectorLabels" . | nindent 4 }}
